server:
  port: 9000
  include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost/rampapp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true